name: Test

on: [push, pull_request]

jobs:
  run-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup override set nightly

      - name: Build with Makefile
        run: make